baseurl = "/"
languageCode = "en-us"
title = "jhaarala's DASC 1104 Blog"
theme = "hugo-lithium"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$", "tidytuesday"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/jhaarala23/dasc1104-blog"
[[menu.main]]
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/jacob-haarala-2a683b1b8/"
[[menu.main]]
    name = "Resume"
    url = "/resume-master/resume-example.pdf"

[params]
    description = "A website built through Hugo and blogdown."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    # path to the favicon, under "static"
    favicon = "favicon.ico"

    [params.logo]
    url = "art-picture.jpg"
    width = 50
    height = 50
    alt = "Logo"

